framework:
    messenger:
        default_bus: messenger.bus.default
        transports:
            async: # nom du transport
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%' # utilise ta base de données
                options:
                    table_name: messenger_messages
        routing:
            'App\Message\SendConfirmationEmail': async